### ISSUE TITLE
The "DXVcsTools" menu shortcuts look weird and don't respect if the shortcuts are changed in the settings

### ISSUE THREAD

**Issue by FedorSafronov** [Xarlot/DXVcsTools#14]
The "show tool window" shortcut is set to "Ctrl+V, T"
![vs_settings](https://cloud.githubusercontent.com/assets/12965713/8253433/7c53cbc4-1698-11e5-8e82-73b3da89eda1.png)
while the menu is still showing "Ctrl+E, T" and the overall shortcut style is a bit weird
![tool_shortcuts](https://cloud.githubusercontent.com/assets/12965713/8253438/80fb313a-1698-11e5-906f-3482bb980ebe.png)
as compared to usual VS shortcuts.
![usual_shortcuts](https://cloud.githubusercontent.com/assets/12965713/8253441/839a6398-1698-11e5-9aa1-626c2b084bb0.png)

**Comment by Xarlot** [comment]
fixed in 2.2.9
