### ISSUE TITLE
Merge without review on modified file (readonly off) cause rewrite file and loose previous changes

### ISSUE THREAD

**Issue by Khranovskiy** [Xarlot/DXVcsTools#15]
Expected: 
  store .back backup file with prev changes

Example :
2015.2:  fileA changed (but undo checkout - leave : readonly false)  (state1-State2)

2015.1 fileA (state1-state3), fileB changes
In 2015.1 merge changes to 15.2,  fileA will have state3 ,

**Comment by Xarlot** [comment]
wont fix
предлагаемое поведение будет генерить кучу мусора на диске
